### Test: Basic Successful Conversion auto_response_mp3_payload_returned_in_body.js
POST http://localhost:3007/convert
Content-Type: multipart/form-data; boundary=----123

------123
Content-Disposition: form-data; name="file"; filename="short.aiff"
Content-Type: audio/aiff

< /Users/Zouhir/Documents/NODE2/aiffamp3_documents/audios/audio-convert-testing-3/short.aiff
------123--